### ISSUE TITLE
Backend worker monitoring thread interrupted or backend worker process died

### ISSUE THREAD

**Issue by ppengkkang** [mukut03/ESG-BERT#2]
When starting the server, I got this error, any idea?

2021-01-08 15:35:44,952 [DEBUG] W-9002-bert_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-08 15:35:44,952 [INFO ] W-9002-bert_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.model = AutoModelForSequenceClassification.from_pretrained(model_dir)

**Comment by leejamesss** [comment]
You can check your model_dir folder and see if pytorch_model.bin is correctly replaced,if correct,then the size of the file should be 400M+
